#!/bin/bash

# is /mnt/hennecke mounted?
if [ -z "$(mount|grep '//hennecke/share')" ]; then
	echo "hennecke not mounted"
	exit
fi

HOSTNAME=$(hostname -s)
DATE=$(date +%Y%m%d)
mkdir -p /mnt/hennecke/backup/$HOSTNAME
echo "dd if=/dev/mmcblk0 bs=1M | gzip > /mnt/hennecke/backup/$HOSTNAME/$DATE.img.gz"
dd if=/dev/mmcblk0 bs=1M | gzip > /mnt/hennecke/backup/$HOSTNAME/$DATE.img.gz
