#!/bin/bash

# build OpenCV with CUDA and cuDNN support

# set -x

source ~/.bashrc
VERSION=4.13.0

echo "building and installing OpenCV and cv2 version $VERSION"

echo make sure CUDA toolkit is installed
sudo apt-get -q install cuda-toolkit

# CUDO NVcc is incompatible with newer gcc compilers
sudo apt-get -q install gcc-12 g++-12

# check whether uv is install and if not install it

if command -v uv >/dev/null 2>&1; then
  echo "uv version: $(uv --version)"
else
  echo "install uv"
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi

cd
mkdir -p cv2-cuda
cd cv2-cuda

WORKDIR=$(pwd)

uv python install
uv venv --clear
source .venv/bin/activate
uv pip install numpy


git clone --branch $VERSION --depth 1 https://github.com/opencv/opencv.git
git clone --branch $VERSION --depth 1 https://github.com/opencv/opencv_contrib.git

echo "Procced with the installation"
cd opencv
mkdir build
cd build

cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D CMAKE_C_COMPILER=/usr/bin/gcc-12 \
-D CMAKE_CXX_COMPILER=/usr/bin/g++-12 \
-D WITH_TBB=ON \
-D ENABLE_FAST_MATH=1 \
-D CUDA_FAST_MATH=1 \
-D WITH_CUBLAS=1 \
-D WITH_CUDA=ON \
-D BUILD_opencv_cudacodec=OFF \
-D WITH_CUDNN=ON \
-D OPENCV_DNN_CUDA=ON \
-D CUDA_ARCH_BIN=8.6 \
-D WITH_V4L=ON \
-D WITH_QT=OFF \
-D WITH_OPENGL=ON \
-D WITH_GSTREAMER=ON \
-D OPENCV_GENERATE_PKGCONFIG=ON \
-D OPENCV_PC_FILE_NAME=opencv.pc \
-D OPENCV_ENABLE_NONFREE=ON \
-D OPENCV_EXTRA_MODULES_PATH=$WORKDIR/opencv_contrib/modules \
-D INSTALL_PYTHON_EXAMPLES=OFF \
-D INSTALL_C_EXAMPLES=OFF \
-D BUILD_EXAMPLES=OFF ..

# -D OPENCV_PYTHON3_INSTALL_PATH=~/.virtualenvs/opencv/lib/python3.12/site-packages/ \
# -D PYTHON_EXECUTABLE=~/.virtualenvs/opencv/bin/python \
