#!/bin/bash
#
# started by cron every five minutes
#
# check if the wifi connection is still alive
#
# if not than restart connection
#
# echo on
# set -x

# check if there is Wifi 
# does it have an address?
if ping -c 1 -W 1 192.168.1.1 &> /dev/null; then
	logger -t "${0##*/}" up: $IP
	echo connected
else
	logger -t "${0##*/}" "connection down! attempting reconnection"
	echo "${0##*/}" "connection down! attempting reconnection"
	ip link set wlan0 down
	sleep 10
	ip link set wlan0 up
fi
