#!/bin/bash
#
# started by cron every five minutes
#
# check if the wifi connection is still alive
#
# if not than restart connection
#

# check if there is Wifi USB dongle plugged in
if lsusb | grep -q "Ralink"; then
  # does it have an address?
  IP=$(ifconfig wlan0 | grep "inet addr:" | cut -d":" -f2| cut -d" " -f1)
  if [ ! -z "$IP" ]; then
    logger -t "${0##*/}" up: $IP
  else
    logger -t "${0##*/}" "connection down! attempting reconnection"
    ifdown --force wlan0
    sleep 10
    ifup --force wlan0
    ifconfig wlan0
  fi
fi
