#!/bin/bash

# is /mnt/hennecke mounted?
echo "checking whether hennecke is mounted ..."
if [ -z "$(mount|grep '//hennecke/share')" ]; then
	echo "hennecke not mounted"
	exit
fi

HOSTNAME=$(hostname -f)
DATE=$(date +%Y%m%d)

# we're in .../exif but want to know the name of the directory
# one level up
TGTDIR=/mnt/hennecke/timelapse/$HOSTNAME/$(echo $PWD | awk -F \/ '{print $(NF-1)}')
mkdir -p $TGTDIR
for jpg in *.jpg
do
	cp -uv $jpg $TGTDIR
done
