#!/bin/bash

if [ -n "$DEBUG" ]; then
  set -x
fi

BASE="$HOME/archive/movies"
BITRATE=3000k
CRF=23
POSITION="unknown"

pwd | grep river
if [ $? -eq 0 ]; then
  POSITION="river"
fi

pwd | grep street
if [ $? -eq 0 ]; then
  POSITION="street"
fi

if [ $POSITION == "unknown" ]; then
  echo "don't know where I am"
  echo "can't find river nor street in current path"
  echo "exit"
  exit
fi

echo "direction is $POSITION"

cd $1
EXIF=$(stat -c%n exif*)
if [ $?  -eq 0 ]
then
  # in case there is more than one exif*, just pick the first
  EXIF=$(stat -c%n exif*|head -1)
  echo "processing $EXIF"
else
  echo "start process of $(pwd)"
  process-tl-dir -v 1
  EXIF=$(stat -c%n exif*|head -1)
fi
cd $EXIF
mkmov -c hevc -2 -q $CRF -b $BITRATE
YEAR=$(stat -c%n *.mp4| head -1 | cut -b1-4)
if [ $? -ne 0 ]; then
  echo "couldn't find output mp4"
  exit
fi

MONTH=$(stat -c%n *.mp4| head -1 | cut -b6-7)
mkdir -p $BASE/{webm,x265}
TGTDIR="$YEAR/$MONTH-$(date -d "$YEAR-$MONTH-01" +%B)"
mkdir -p $BASE/x265/$POSITION/$TGTDIR
mv -v *.mp4 $BASE/x265/$POSITION/$TGTDIR

mkmov -c vp9 -2 -q $CRF -b $BITRATE
YEAR=$(stat -c%n *.webm| head -1 | cut -b1-4)

if [ $? -ne 0 ]; then
  echo "couldn't find output webm"
  exit
fi

MONTH=$(stat -c%n *.webm| head -1 | cut -b6-7)
TGTDIR="$YEAR/$MONTH-$(date -d "$YEAR-$MONTH-01" +%B)"
mkdir -p $BASE/webm/$POSITION/$TGTDIR
mv -v *.webm $BASE/webm/$POSITION/$TGTDIR
cd ..
rm -rf exif*
cd ..

