#!/bin/bash

if [ -n "$DEBUG" ]; then
  set -x
fi

if [ -z "$1" ]; then
  echo missing directory with timelapse jpgs to process
  exit 1
fi


# BASE="$HOME/archive/movies"
BASE="/usb_drives/my_book/archive/movies"
BITRATE=5000k
CRF=23
POSITION="river"

cd $1
EXIF=$(stat -c%n exif*)
if [ $?  -eq 0 ]
then
  # in case there is more than one exif*, just pick the first
  EXIF=$(stat -c%n exif*|head -1)
  echo "processing $EXIF"
else
  echo "start process of $(pwd)"
  process-tl-dir -v 1
  EXIF=$(stat -c%n exif*|head -1)
fi
cd $EXIF
# mkmov -c hevc -2 -q $CRF -b $BITRATE -v
mkmov -2 -c libsvtav1 -q $CRF -b 5000K -v
YEAR=$(stat -c%n *.mp4| head -1 | cut -b1-4)
if [ $? -ne 0 ]; then
  echo "couldn't find output mp4"
  exit
fi

MONTH=$(stat -c%n *.mp4| head -1 | cut -b6-7)
mkdir -p $BASE/x265
TGTDIR="$YEAR/$MONTH-$(date -d "$YEAR-$MONTH-01" +%B)"
mkdir -p $BASE/x265/$POSITION/$TGTDIR
mv -v *.mp4 $BASE/x265/$POSITION/$TGTDIR

cd ..
if [ "$DEBUG" != "1" ]; then
  rm -rf exif*
fi

cd ..

