#!/bin/bash

START_TIME=$SECONDS
OPT="-hide_banner -v info -y"
QUALITY=${Q:-33}
# ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow
PRESET=${PRESET:-medium}
MOVIE=$(stat -c"%y" tl000001.jpg|cut -d " " --output-delimiter=- -f1,2|cut -b1-10)-x264-q$QUALITY-$PRESET.mp4
echo -n create_movie $MOVIE ... 

# run faster if interactive
if [ -z !$PID ]; then
	ffmpeg $OPT -r 30 -f image2 -i tl%06d.jpg -vf "hqdn3d=1.5:1.5:6:6" -an -preset slow -c:v libx264 -crf $QUALITY -r 30 $MOVIE
else
	ffmpeg $OPT -r 30 -f image2 -i tl%06d.jpg -vf "hqdn3d=1.5:1.5:6:6" -an -preset $PRESET -c:v libx264 -crf $QUALITY -r 30 $MOVIE
fi
ELAPSED_TIME=$(($SECONDS - $START_TIME))
echo finished in $(($ELAPSED_TIME/60/60)) hr, $(($ELAPSED_TIME/60%60)) min and $(($ELAPSED_TIME % 60)) sec
