#!/usr/bin/env ruby

require 'sun_times'

jetzt = Time.now
lat = ENV['LAT']
lon = ENV['LON']
sun = SunTimes.new

if jetzt > sun.rise(jetzt, lat, lon) && jetzt < sun.set(jetzt, lat, lon)
	print "-ex backlight -mm backlit"
else
	print "-ex night"
end

