#!/usr/bin/env ruby

require "httpclient"
require "awesome_print"
require "json"
require 'sun_times'

c = HTTPClient.new
begin
	r = c.get_content("http://freegeoip.net/json/")
rescue Exception => e
	print "Error: ", e, "\n"
	print "exiting ...\n"
	exit
end
geo_data = JSON.parse(r)
ap geo_data

jetzt = Time.now
lat = geo_data['latitude']
lon = geo_data['longitude']
sun = SunTimes.new

print "Sunrise: ", sun.rise(jetzt, lat, lon).localtime.strftime("%X"), "\n"
print "Sunset : ", sun.set(jetzt, lat, lon).localtime.strftime("%X"), "\n"
