#!/bin/sh

sudo install -Cv -g staff jpg2mp4 check-disks daily-motion daily-motion-all concat-footage hourly_motion create-archive create-24h-movie hourly.job daily.job monthly concat-daily-movies fill-gaps create-foto-index send-ip-addr foto day-or-night cpu-data check-wifi timelapse insert-exif create-vp9 create-x264 create-hevc mkmov geo-coord geo-coord wrap-timelapse process-tl-dir record-movie tl2mp4 /usr/local/bin
