#!/bin/sh

sudo install -Cv -g staff ffmpeg ffprobe ffplay daily-motion concat-footage hourly_motion create-av1 create-archive create-24h-movie hourly.job daily.job monthly concat-daily-movies fill-gaps create-foto-index send-ip-addr foto day-or-night cpu-data check-wifi timelapse insert-exif create-vp9 create-x264 create-hevc mkmov geo-coord geo-coord wrap-timelapse process-tl-dir record-movie check-internet /usr/local/bin
