#!/bin/bash

set -x

DIR=$(pwd)
OUTPUT=$(basename $DIR)
# ffmpeg -y -hide_banner -r 30 -pattern_type glob -i '*.jpg' -vf "scale=-1:1080" -c:v hevc_nvenc -r 30 -b:v 1500K ../$OUTPUT.mp4
ffmpeg -y -hide_banner -r 30 -pattern_type glob -i '*.jpg' -vf "scale=-1:1080" -c:v h264_nvenc -r 30 -b:v 1500K ../$OUTPUT.mp4
