#!/bin/bash
#

START_TIME=$SECONDS

# defaults
WIDTH=1024
LOG_LEVEL=info
BITRATE=2500k
QUALITY=28
TWOPASS=0
FRAMERATE=24
PRESET=medium

FDATE=$(stat -c"%y" tl000001.jpg|cut -b1-10)
DATUM=$(stat -c"%y" tl000001.jpg|cut -b1-10|perl -npe "s/(\d+)\-(\d+)\-(\d+)/\3.\2.\1/")

if [ -z $FDATE ]; then
	echo "couldn't find tl000001.jpg"
	echo "wrong directory?"
	exit
fi

if [ "-"  = "${1:0:1}" ]; then
	echo first parameter has to be x264, hevc or vp9
	exit
fi

CODEC=$1
if  [ $CODEC != "x264" ] && 
	[ $CODEC != "x265" ] && 
	[ $CODEC != "hevc" ] && 
	[ $CODEC != "vp9" ]
then
	echo unknown codec
	echo valid parameters are x264, x265, hevc, vp9
	exit
fi

shift

while getopts w:hv:q:b:2r:p: opt; do
	case $opt in
		w)
			echo "width" $OPTARG
			WIDTH=$OPTARG
			;;
		h)
			echo Help
			;;
		v)
			echo log level $OPTARG
			LOG_LEVEL=$OPTARG
			;;
		q)
			echo quality for CRF $OPTARG
			QUALITY=$OPTARG
			;;
		b)
			echo bitrate $OPTARG
			BITRATE=$OPTARG
			;;
		2)
			echo two pass on
			TWOPASS=1
			;;
		r)
			echo framerate $FRAMERATE fps
			;;
		p)
			echo preset $OPTARG
			echo possible values: ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow
			PRESET=$OPTARG
	esac
done

# movie sizing independent from picture size
SIZING="-vf scale=$WIDTH:-1"
OPT="-y -v $LOG_LEVEL -hide_banner"
MOVIE=$FDATE-$CODEC-q$QUALITY-w$WIDTH-fr$FRAMERATE
MAUTHOR="Steffen Roller <steffen.roller@gmail.com>" 
MYEAR="(c) by Steffen Roller 2017" 
MCOPY="Creative Commons License (BY)" 
MDESC="codec:$CODEC:quality $QUALITY:width $WIDTH:$FRAMERATE fps"
MTITLE="$DATUM, Grand River Kitchener,ON"
METADATA="-metadata title='$MTITLE'"

case $CODEC in
	x264)
		if [ "$TWOPASS" = "1" ]; then
			ffmpeg $OPT -r $FRAMERATE -f image2 -i tl%06d.jpg \
				   -an -preset $PRESET -c:v libx264 \
				   $SIZING \
				   -metadata title="$MTITLE" -metadata author="$MAUTHOR" -metadata year="$MYEAR" -metadata copyright="$MCOPY" -metadata description="$MDESC"\
				   -b:v $BITRATE -pass 1 -r $FRAMERATE -f mp4 /dev/null
			MOVIE=$MOVIE-$PRESET-2pass.mp4
			ffmpeg $OPT -r $FRAMERATE -f image2 -i tl%06d.jpg \
				   -an -preset $PRESET -c:v libx264 \
				   $SIZING \
				   -metadata title="$MTITLE" -metadata author="$MAUTHOR" -metadata year="$MYEAR" -metadata copyright="$MCOPY" -metadata description="$MDESC"\
				   -b:v $BITRATE -pass 2 -r $FRAMERATE $MOVIE
		else # single pass
			MOVIE=$MOVIE-$PRESET.mp4
			ffmpeg $OPT -r $FRAMERATE -f image2 -i tl%06d.jpg \
				   -an -preset $PRESET -c:v libx264 \
				   $SIZING \
				   -metadata title="$MTITLE" -metadata author="$MAUTHOR" -metadata year="$MYEAR" -metadata copyright="$MCOPY" -metadata description="$MDESC"\
				   -crf $QUALITY -r $FRAMERATE $MOVIE
		fi
		;;
	vp9)
		if [ "$TWOPASS" = "1" ]; then
			ffmpeg $OPT -r $FRAMERATE -f image2 -i tl%06d.jpg \
				   -c:v libvpx-vp9 -pass 1 -b:v 0 \
				   $SIZING \
				   -crf $QUALITY -threads 8 -speed 4 -tile-columns 6 -frame-parallel 1 -an -f webm /dev/null 
			MOVIE=$MOVIE-2pass.webm
			ffmpeg $OPT -r $FRAMERATE -f image2 -i tl%06d.jpg -c:v libvpx-vp9 -pass 2 -b:v 0 \
				   $SIZING \
				   -metadata title="$MTITLE" -metadata author="$MAUTHOR" -metadata year="$MYEAR" -metadata copyright="$MCOPY" -metadata description="$MDESC"\
				   -crf $QUALITY -threads 8 -speed 1 -tile-columns 6 -frame-parallel 1 -auto-alt-ref 1 -lag-in-frames 25 -an -r $FRAMERATE -f webm $MOVIE
			rm ffmpeg2pass-0.log
		else
			MOVIE=$MOVIE-1pass.webm
			ffmpeg $OPT -r $FRAMERATE -f image2 -i tl%06d.jpg \
				   $SIZING \
				   -metadata title="$MTITLE" -metadata author="$MAUTHOR" -metadata year="$MYEAR" -metadata copyright="$MCOPY" -metadata description="$MDESC"\
				   -an -c:v libvpx-vp9 -crf $QUALITY -b:v 0 -r $FRAMERATE $MOVIE
		fi
		;;
	hevc|x265)
		MOVIE=$MOVIE-2pass.mp4
		if [ "$TWOPASS" = "1" ]; then
			ffmpeg $OPT -r $FRAMERATE -f image2 -i tl%06d.jpg \
				   -an -c:v libx265 \
				   $SIZING \
				   -metadata title="$MTITLE" -metadata author="$MAUTHOR" -metadata year="$MYEAR" -metadata copyright="$MCOPY" -metadata description="$MDESC"\
				   -b:v $BITRATE -pass 1 -r $FRAMERATE -f mp4 /dev/null
			MOVIE=$MOVIE-$PRESET-2pass.mp4
			ffmpeg $OPT -r $FRAMERATE -f image2 -i tl%06d.jpg \
				   -an -c:v libx265 \
				   $SIZING \
				   -metadata title="$MTITLE" -metadata author="$MAUTHOR" -metadata year="$MYEAR" -metadata copyright="$MCOPY" -metadata description="$MDESC"\
				   -b:v $BITRATE -pass 2 -r $FRAMERATE $MOVIE
		else # single pass
			ffmpeg $OPT -r $FRAMERATE -f image2 -i tl%06d.jpg \
				   $SIZING \
				   -metadata title="$MTITLE" -metadata author="$MAUTHOR" -metadata year="$MYEAR" -metadata copyright="$MCOPY" -metadata description="$MDESC"\
				   -an \
				   -c:v libx265 -crf $QUALITY -r $FRAMERATE $MOVIE
		fi
		;;
esac

ELAPSED_TIME=$(($SECONDS - $START_TIME))
echo output $MOVIE
echo finished in $(($ELAPSED_TIME/60/60)) hr, $(($ELAPSED_TIME/60%60)) min and $(($ELAPSED_TIME % 60)) sec

