#!/bin/bash

TEKSAVVY=mysavvy.teksavvy.com
GOOGLE=www.google.com
LOG=$HOME/var/log/network_monitor.log

echo "start at $(date)"
echo "start at $(date)" >> $LOG

while true
do
  # curl --head -s https://$TEKSAVVY > /dev/null
  if ping -c 1 -W 1 $TEKSAVVY &> /dev/null; then
    echo -en "$(date +%H:%M:%S)\r"
  else
    # couldn't connect to outside world
    RC=$?
    echo
    echo "$(date +%Y%m%d-%H%M%S): $(basename $0): ping to $TEKSAVVY failed with rc=$RC"
    echo "$(date +%Y%m%d-%H%M%S): $(basename $0): ping to $TEKSAVVY failed with rc=$RC" >> $LOG

    # check our wifi
    curl --head -s http://192.168.1.1/webpages/login.html > /dev/null
    if [ $? -eq 0 ]; then
      echo "$(date +%Y%m%d-%H%M%S): $(basename $0): curl to router OK"
      logger -t $(basename $0) "curl to router ok"
    else
      echo "$(date +%Y%m%d-%H%M%S): $(basename $0): curl to router NOT ok"
      logger -t $(basename $0) "curl to router failed, Wifi issue?"
    fi
    logger -t $(basename $0)  "curl to $URL failed with exit code $RC"
  fi
  sleep 7
done
