#!/bin/sh

if [ $IFACE = "lo" ]; then
  exit
fi

if [ $IFACE = "--all" ]; then
  exit
fi

logger $IFACE up

IP_ADDR=$(ifconfig $IFACE | grep "inet addr:" | awk '{ print $2 }' | cut -d: -f2)

if [ -z $IP_ADDR ]; then
	exit
fi

TIME=$(date)

logger $IFACE IP_ADDR $IP_ADDR
mailx -s "$HOSTNAME ip number" steffen.roller@gmail.com <<EOM

Time: $TIME

interface $IFACE connected

I am online at: $IP_ADDR

http://$IP_ADDR:4000

EOM
