#!/bin/bash

sudo tail -n 20 -f /var/log/nginx/access.log /var/log/nginx/error.log | awk '
{
  # print ">> "$0 " <<"
  # replace ip number with hostname
  if ($0 !~ /\/var\/log/) {
    if ($1 != "") {
        cmd="~/bin/ip_to_host " $1
        cmd | getline name
        close(cmd)
        $1 = name
    }
  }

  if ($9 ~ /^4[0-9]{2}$/) {
    print "\033[0;31m" $0 "\033[0m"
  } else {
  print $0
}
}'
