#!/bin/bash

# tmux new -d -s "update-all"
for node in europa.local io.local ganymede.local callisto.local titan.local phobos.local pi-hole.local
do
  echo -ne "\033]0;updating $node\007"
  echo '************************************'
  echo "         $node"
  echo '************************************'
  echo connecting ...
  ssh $node "uname -a ; sudo apt-get update ; sudo apt-get -y upgrade ; sudo apt-get -y dist-upgrade ; sudo apt-get -y autoremove" 
  echo '************************************'
  echo "         $node done"
  echo '************************************'
done

echo '************************************'
echo "         pihole -up"
echo '************************************'
ssh steffenr@pi-hole.local "pihole -up"
