#!/bin/bash

INPUT_DIR=$(cat ~/tmp/timelapse.dir)
OUTPUT_DIR=exif

if [ -d $INPUT_DIR ]; then
  cd $INPUT_DIR
  echo INPUTDIR=$INPUT_DIR
  insert-exif $OUTPUT_DIR tl*.jpg
  cd $OUTPUT_DIR
  TGTDATE=$(identify -format %[EXIT:DateTime] tl000001.jpg|cut -b1-10|cut -d":" -f1,2,3 --output-delimiter="")
  TGTDIR=/mnt/hennecke/timelapse/pi/$TGTDATE
  START_TIME=$SECONDS
  mkdir -p $TGTDIR
  FILES=$(cp -v tl*.jpg $TGTDIR|wc -l)
  ELAPSED_TIME=$(($SECONDS - $START_TIME))
  echo copied $FILES from $OUTPUT_DIR to $TGTDIR in $(($ELAPSED_TIME/60/60)) hr, $(($ELAPSED_TIME/60%60)) min and $(($ELAPSED_TIME % 60)) sec
  create-movie
  mv -v *.mp4 ~/movies
  cd ~/timelapse
else
  echo directory $INPUT_DIR not found
fi
