#!/bin/bash

DIR=~/tmp/timelapse.dir
INPUT_DIR=$(cat ~/tmp/timelapse.dir)

OUTPUT_DIR=exif

if [ ! -f $DIR ]; then
	logger -s "$DIR doesn't exist"
	logger -s "abort"
	exit
fi

if [ -d $INPUT_DIR ]; then
  cd $INPUT_DIR
  echo INPUTDIR=$INPUT_DIR
  # insert-exif $OUTPUT_DIR tl*.jpg

  # ab hier sollte jetzt alles auf dem nfs server laufen
  # remote call to beaglebone.local
#  process-tl-dir
#  cd $OUTPUT_DIR
#  TGTDATE=$(basename $INPUT_DIR)
#  TGTDIR=/mnt/hennecke/timelapse/$(hostname)/$TGTDATE
#  START_TIME=$SECONDS
#  mkdir -p $TGTDIR
#  FILES=$(cp -vur tl*.jpg $TGTDIR|wc -l)
#  ELAPSED_TIME=$(($SECONDS - $START_TIME))
#  echo copied $FILES from $OUTPUT_DIR to $TGTDIR in $(($ELAPSED_TIME/60/60)) hr, $(($ELAPSED_TIME/60%60)) min and $(($ELAPSED_TIME % 60)) sec
#  create-movie
#  mkdir -p ~/movies
#  # wir mappen jetzt eine externe USB festplatte über nfs
#  # cp -v *.mp4 /mnt/hennecke/timelapse/$(hostname)/movies
#  mv -v *.mp4 ~/movies
#  cd ~/timelapse
else
  echo directory $INPUT_DIR not found
fi
